<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
?>



<?php $this->trigger('view.show.before'); ?>
<?php if ($item->media()): ?>
<div>
<?php echo $this->universalViewer($item); ?>
</div>
<?php endif; ?>
<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
<?php echo $item->displayValues(); ?>


<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>

<?php $this->trigger('view.show.after'); ?>