<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();

?>

<?php foreach ($item->media() as $media): ?>
    <?php $mediaType = $media->mediaType(); ?>
    <?php $mediaRenderer = $media->renderer(); ?>
    <?php if ((strpos($mediaType, 'image') !== false) || (strpos($mediaRenderer, 'youtube') !== false)): ?>
        <?php $lightMedia[] = $media; ?>
    <?php else: ?>
        <?php $otherMedia[] = $media; ?>
    <?php endif; ?>
<?php endforeach; ?>

<?php echo $this->pageTitle($item->displayTitle(), 2); ?>
<?php $this->trigger('view.show.before'); ?>
<?php if ($item->media()): ?>
<img src="<?php echo $escape($media->thumbnailUrl('medium')); ?>" />
<?php endif; ?>
<?php echo $item->displayValues(); ?>
<div class="property">
    <?php $itemSets = $item->itemSets(); ?>
    <?php if (count($itemSets) > 0): ?>
    <h4><?php echo $translate('Item sets'); ?></h4>
    <?php foreach ($itemSets as $itemSet): ?>
    <div class="value"><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></div>
    <?php endforeach; ?>
    <?php endif; ?>
</div>


<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->displaySubjectValues($page, 25, $property);
?>
<?php if ($subjectValues): ?>
<h3>Aineistoon liittyvää</h3>
<div id="item-linked">
    <?php echo $subjectValues; ?>
</div>
<?php endif; ?>

<?php $this->trigger('view.show.after'); ?>
